# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KinokzCopy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'FSCalendar'


  # Pods for KinokzCopy

  target 'KinokzCopyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KinokzCopyUITests' do
    # Pods for testing
  end

end
